title: El Vampiro de la Colonia Roma
description: A Spanish-English reference guide
theme: just-the-docs

url: https://just-the-docs.github.io



items:
- title: "Link 1"
  url: "/link1/"
- title: "Link 2"
  url: "/link2/"
- title: "Link 3"
  url: "/link3/"


# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-V07VL6ELS7
ga_tracking_anonymize_ip: true #

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
